# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170120_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
